services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.local
    container_name: boostad-nginx-local
    ports:
      - '80:80'
      - '443:443'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    networks:
      - boostad-local

  redis:
    image: redis/redis-stack-server:latest
    container_name: boostad-redis-master-local
    ports:
      - '16379:6379'
    environment:
      - REDIS_ARGS=--protected-mode no --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru --save 900 1 --save 300 10 --save 60 10000
    volumes:
      - redis-master-data:/data
    restart: unless-stopped
    networks:
      - boostad-local

  mysql:
    image: mysql:8.0
    container_name: boostad-mysql-local
    ports:
      - '13306:3306' # 호스트 13306 -> 컨테이너 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-test_user}
      MYSQL_DATABASE: ${DB_DATABASE:-test_db}
      MYSQL_USER: ${DB_USERNAME:-test_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-test_user}
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro # 초기화 스크립트 -> 파일 순서대로 실행
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+09:00
      - --log-bin-trust-function-creators=1
    restart: unless-stopped
    networks:
      - boostad-local

  kafka:
    image: apache/kafka:3.8.1
    container_name: boostad-kafka-local
    ports:
      - '19092:19092'
    environment:
      KAFKA_NODE_ID: '1'
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: unless-stopped
    networks:
      - boostad-local

volumes:
  redis-master-data:
  mysql-data:
  kafka-data:

networks:
  boostad-local:
    driver: bridge
