import { CampaignServingSnapshotService } from './campaign-serving-snapshot.service';
import { CampaignCacheRepository } from './repository/campaign.cache.repository.interface';
import type { CachedCampaign } from './types/campaign.types';
import { ConfigService } from '@nestjs/config';
import type { AppIORedisClient } from '../redis/redis.type';
import type { CampaignSearchRepository } from './repository/campaign-search.repository.interface';

describe('CampaignServingSnapshotService', () => {
  const embedding = Array.from({ length: 384 }, (_, index) => index / 384);

  const buildCampaign = (
    id: string,
    embeddingTags: Record<string, number[]> = { tag: embedding }
  ): CachedCampaign => ({
    id,
    userId: 1,
    servingVersion: 1,
    title: id,
    content: 'content',
    image: null,
    url: 'https://example.com',
    maxCpc: 100,
    dailyBudget: 1000,
    totalBudget: 10000,
    dailySpent: 0,
    totalSpent: 0,
    lastResetDate: new Date().toISOString(),
    isHighIntent: false,
    status: 'ACTIVE',
    startDate: new Date(Date.now() - 60_000).toISOString(),
    endDate: new Date(Date.now() + 60_000).toISOString(),
    createdAt: new Date().toISOString(),
    deletedAt: null,
    tags: ['tag'],
    embeddingTags,
  });

  const buildRepository = (campaigns: CachedCampaign[]) =>
    ({
      getAllCampaigns: jest.fn().mockResolvedValue(campaigns),
      findCampaignCachesByIds: jest.fn((ids: string[]) =>
        Promise.resolve(
          campaigns.filter((campaign) => ids.includes(campaign.id))
        )
      ),
    }) as unknown as CampaignCacheRepository & {
      getAllCampaigns: jest.Mock;
      findCampaignCachesByIds: jest.Mock;
    };

  const configService = {
    get: jest.fn((key: string, defaultValue?: string) => {
      if (key === 'RTB_CAMPAIGN_SOURCE') return 'local_snapshot';
      if (key === 'RTB_EMBEDDING_PROFILE') return 'legacy_minilm';
      if (key === 'RTB_DENSE_RETRIEVAL_MODE') return 'legacy_tag';
      return defaultValue;
    }),
  } as unknown as ConfigService;

  const productDefaultConfigService = {
    get: jest.fn((key: string, defaultValue?: string) =>
      key === 'RTB_CAMPAIGN_SOURCE' ? 'local_snapshot' : defaultValue
    ),
  } as unknown as ConfigService;

  it('builds the initial snapshot only once for concurrent reads', async () => {
    const campaign = buildCampaign('c1');
    const repository = buildRepository([campaign]);
    const service = new CampaignServingSnapshotService(
      repository,
      configService
    );

    const [first, second] = await Promise.all([
      service.findCampaignsByIds(['c1']),
      service.findCampaignsByIds(['c1']),
    ]);

    expect(first.map((item) => item.id)).toEqual(['c1']);
    expect(second.map((item) => item.id)).toEqual(['c1']);
    expect(first[0].embeddingTags?.tag).toBeInstanceOf(Float32Array);
    for (const excludedField of [
      'dailyBudget',
      'totalBudget',
      'dailySpent',
      'totalSpent',
      'lastResetDate',
      'createdAt',
    ]) {
      expect(first[0]).not.toHaveProperty(excludedField);
    }
    expect(repository.getAllCampaigns).toHaveBeenCalledTimes(1);
    expect(repository.findCampaignCachesByIds).not.toHaveBeenCalled();
  });

  it('requires the E5 document embedding in the default serving mode', async () => {
    const campaign = {
      ...buildCampaign('c1'),
      embeddingModelVersion:
        'Xenova/multilingual-e5-small@retrieval-v1-mean-normalized',
      embeddingDocument: embedding,
    };
    const repository = buildRepository([campaign]);
    const service = new CampaignServingSnapshotService(
      repository,
      productDefaultConfigService
    );

    const campaigns = await service.findCampaignsByIds(['c1']);

    expect(campaigns[0].embeddingDocument).toBeInstanceOf(Float32Array);
    expect(repository.findCampaignCachesByIds).not.toHaveBeenCalled();
  });

  it('returns campaigns in ANN ID order', async () => {
    const first = buildCampaign('c1');
    const second = buildCampaign('c2');
    const repository = buildRepository([first, second]);
    const service = new CampaignServingSnapshotService(
      repository,
      configService
    );

    const campaigns = await service.findCampaignsByIds(['c2', 'c1']);

    expect(campaigns.map((campaign) => campaign.id)).toEqual(['c2', 'c1']);
  });

  it('repairs a campaign whose embeddings were generated by another process', async () => {
    const incomplete = buildCampaign('c1', {});
    const completed = buildCampaign('c1');
    const repository = buildRepository([incomplete]);
    repository.findCampaignCachesByIds.mockResolvedValue([completed]);
    const service = new CampaignServingSnapshotService(
      repository,
      configService
    );

    const campaigns = await service.findCampaignsByIds(['c1']);

    expect(repository.findCampaignCachesByIds).toHaveBeenCalledWith(['c1']);
    expect(campaigns.map((campaign) => campaign.id)).toEqual(['c1']);
    expect(campaigns[0].embeddingTags?.tag).toBeInstanceOf(Float32Array);
  });

  it('does not admit an index-unready repair into the safe snapshot', async () => {
    const incomplete = {
      ...buildCampaign('c1', {}),
      indexReady: false,
    };
    const repository = buildRepository([incomplete]);
    const service = new CampaignServingSnapshotService(
      repository,
      configService
    );

    await expect(service.findCampaignsByIds(['c1'])).resolves.toEqual([]);
    await expect(service.findCampaignsByTags(['tag'])).resolves.toEqual([]);
  });

  it('applies cache mutations without rebuilding the whole snapshot', async () => {
    const first = buildCampaign('c1');
    const second = buildCampaign('c2');
    const repository = buildRepository([first]);
    const service = new CampaignServingSnapshotService(
      repository,
      configService
    );
    await service.findCampaignsByIds(['c1']);
    const previousVersion = service.getMetadata().version;

    service.onCampaignCacheUpserted({ campaign: second });
    service.onCampaignCacheRemoved({ campaignId: 'c1' });

    await expect(
      service
        .findCampaignsByIds(['c2'])
        .then((campaigns) => campaigns.map((campaign) => campaign.id))
    ).resolves.toEqual(['c2']);
    expect(service.getMetadata()).toMatchObject({
      version: previousVersion + 2,
      size: 1,
    });
  });

  it('serves normalized tag unions from the local inverted index', async () => {
    const first = {
      ...buildCampaign('c1'),
      tags: ['React', 'TypeScript'],
      embeddingTags: { React: embedding, TypeScript: embedding },
    };
    const second = {
      ...buildCampaign('c2'),
      tags: ['Redis'],
      embeddingTags: { Redis: embedding },
    };
    const repository = buildRepository([first, second]);
    const service = new CampaignServingSnapshotService(
      repository,
      configService
    );

    const campaigns = await service.findCampaignsByTags([
      ' react ',
      'REDIS',
      'react',
    ]);

    expect(campaigns.map((campaign) => campaign.id)).toEqual(['c1', 'c2']);
    expect(service.getMetadata().tagCount).toBe(3);
    expect(repository.findCampaignCachesByIds).not.toHaveBeenCalled();
  });

  it('keeps the tag index synchronized with upsert and remove events', async () => {
    const first = {
      ...buildCampaign('c1'),
      tags: ['before'],
      embeddingTags: { before: embedding },
    };
    const updated = {
      ...buildCampaign('c1'),
      tags: ['after'],
      embeddingTags: { after: embedding },
    };
    const repository = buildRepository([first]);
    const service = new CampaignServingSnapshotService(
      repository,
      configService
    );
    await service.findCampaignsByTags(['before']);

    service.onCampaignCacheUpserted({ campaign: updated });
    await expect(service.findCampaignsByTags(['before'])).resolves.toEqual([]);
    await expect(
      service
        .findCampaignsByTags(['after'])
        .then((campaigns) => campaigns.map((campaign) => campaign.id))
    ).resolves.toEqual(['c1']);

    service.onCampaignCacheRemoved({ campaignId: 'c1' });
    await expect(service.findCampaignsByTags(['after'])).resolves.toEqual([]);
  });

  it('does not lose mutations that arrive while the initial snapshot is loading', async () => {
    const stale = buildCampaign('c1');
    const updated = { ...buildCampaign('c1'), title: 'updated' };
    let finishLoading: ((campaigns: CachedCampaign[]) => void) | undefined;
    const repository = buildRepository([]);
    repository.getAllCampaigns.mockImplementation(
      () =>
        new Promise<CachedCampaign[]>((resolve) => {
          finishLoading = resolve;
        })
    );
    const service = new CampaignServingSnapshotService(
      repository,
      configService
    );

    const readInFlight = service.findCampaignsByIds(['c1']);
    await Promise.resolve();
    service.onCampaignCacheUpserted({ campaign: updated });
    finishLoading?.([stale]);

    const campaigns = await readInFlight;

    expect(campaigns[0].title).toBe('updated');
  });

  it('bootstraps from a head, then replays events that arrived during full load', async () => {
    const initial = { ...buildCampaign('c1'), servingVersion: 1 };
    const updated = {
      ...buildCampaign('c1'),
      servingVersion: 2,
      title: 'updated-by-stream',
      indexReady: true,
    };
    const legacyRepository = buildRepository([]);
    const searchRepository = {
      getAllSearchCampaigns: jest.fn().mockResolvedValue([initial]),
      findCampaignsByIds: jest.fn().mockResolvedValue([updated]),
    } as unknown as CampaignSearchRepository;
    const searchRedis = {
      xrevrange: jest.fn().mockResolvedValue([['10-0', []]]),
      xrange: jest
        .fn()
        .mockResolvedValueOnce([
          [
            '11-0',
            [
              'type',
              'UPSERT',
              'campaignId',
              'c1',
              'servingVersion',
              '2',
              'indexReady',
              '1',
            ],
          ],
        ])
        .mockResolvedValueOnce([]),
    } as unknown as AppIORedisClient;
    const activeConfig = {
      get: jest.fn((key: string, defaultValue?: string) => {
        if (key === 'RTB_CAMPAIGN_SOURCE') return 'local_snapshot';
        if (key === 'RTB_EMBEDDING_PROFILE') return 'legacy_minilm';
        if (key === 'RTB_DENSE_RETRIEVAL_MODE') return 'legacy_tag';
        if (key === 'CAMPAIGN_PROJECTION_MODE') return 'active';
        return defaultValue;
      }),
    } as unknown as ConfigService;
    const service = new CampaignServingSnapshotService(
      legacyRepository,
      activeConfig,
      searchRedis,
      searchRepository
    );

    const campaigns = await service.findCampaignsByIds(['c1']);

    expect(campaigns[0]).toMatchObject({
      servingVersion: 2,
      title: 'updated-by-stream',
    });
    expect(searchRedis.xrevrange).toHaveBeenCalledTimes(1);
    expect(searchRepository.getAllSearchCampaigns).toHaveBeenCalledTimes(1);
    expect(searchRepository.findCampaignsByIds).toHaveBeenCalledWith(['c1']);
  });

  it('does not expose the bootstrap snapshot before Stream replay completes', async () => {
    const initial = { ...buildCampaign('c1'), servingVersion: 1 };
    const updated = {
      ...buildCampaign('c1'),
      servingVersion: 2,
      title: 'replayed-before-ready',
      indexReady: true,
    };
    let finishReplay:
      | ((entries: Array<[string, string[]]>) => void)
      | undefined;
    const searchRepository = {
      getAllSearchCampaigns: jest.fn().mockResolvedValue([initial]),
      findCampaignsByIds: jest.fn().mockResolvedValue([updated]),
    } as unknown as CampaignSearchRepository;
    const searchRedis = {
      xrevrange: jest.fn().mockResolvedValue([['10-0', []]]),
      xrange: jest
        .fn()
        .mockImplementationOnce(
          () =>
            new Promise<Array<[string, string[]]>>((resolve) => {
              finishReplay = resolve;
            })
        )
        .mockResolvedValueOnce([]),
    } as unknown as AppIORedisClient;
    const activeConfig = {
      get: jest.fn((key: string, defaultValue?: string) => {
        if (key === 'RTB_CAMPAIGN_SOURCE') return 'local_snapshot';
        if (key === 'RTB_EMBEDDING_PROFILE') return 'legacy_minilm';
        if (key === 'RTB_DENSE_RETRIEVAL_MODE') return 'legacy_tag';
        if (key === 'CAMPAIGN_PROJECTION_MODE') return 'active';
        return defaultValue;
      }),
    } as unknown as ConfigService;
    const service = new CampaignServingSnapshotService(
      buildRepository([]),
      activeConfig,
      searchRedis,
      searchRepository
    );

    const firstRead = service.findCampaignsByIds(['c1']);
    await new Promise<void>((resolve) => setImmediate(resolve));
    expect(finishReplay).toBeDefined();
    let secondResolved = false;
    const secondRead = service.findCampaignsByIds(['c1']).then((campaigns) => {
      secondResolved = true;
      return campaigns;
    });
    await Promise.resolve();
    expect(secondResolved).toBe(false);

    finishReplay?.([
      [
        '11-0',
        [
          'type',
          'UPSERT',
          'campaignId',
          'c1',
          'servingVersion',
          '2',
          'indexReady',
          '1',
        ],
      ],
    ]);

    await expect(firstRead).resolves.toEqual([
      expect.objectContaining({
        servingVersion: 2,
        title: 'replayed-before-ready',
      }),
    ]);
    await expect(secondRead).resolves.toEqual([
      expect.objectContaining({
        servingVersion: 2,
        title: 'replayed-before-ready',
      }),
    ]);
  });

  it('lets each API snapshot apply the same independent Stream event', async () => {
    const initial = { ...buildCampaign('c1'), servingVersion: 1 };
    const updated = {
      ...buildCampaign('c1'),
      servingVersion: 2,
      title: 'broadcast-update',
      indexReady: true,
    };
    const eventFields = [
      'type',
      'UPSERT',
      'campaignId',
      'c1',
      'servingVersion',
      '2',
      'indexReady',
      '1',
    ];

    const services = [1, 2].map(() => {
      const repository = buildRepository([initial]);
      const searchRepository = {
        getAllSearchCampaigns: jest.fn().mockResolvedValue([initial]),
        findCampaignsByIds: jest.fn().mockResolvedValue([updated]),
      } as unknown as CampaignSearchRepository;
      return {
        service: new CampaignServingSnapshotService(
          repository,
          configService,
          undefined,
          searchRepository
        ),
        searchRepository,
      };
    });

    for (const instance of services) {
      await instance.service.findCampaignsByIds(['c1']);
      await (
        instance.service as unknown as {
          applyStreamEntry(id: string, fields: string[]): Promise<void>;
        }
      ).applyStreamEntry('20-0', eventFields);
    }

    for (const instance of services) {
      await expect(
        instance.service.findCampaignsByIds(['c1'])
      ).resolves.toEqual([
        expect.objectContaining({
          servingVersion: 2,
          title: 'broadcast-update',
        }),
      ]);
      expect(
        instance.searchRepository.findCampaignsByIds
      ).toHaveBeenCalledTimes(1);
    }
  });

  it('detects a reconnect cursor outside the retained Stream range', async () => {
    const repository = buildRepository([]);
    const searchRedis = {
      xrange: jest.fn().mockResolvedValue([['200-0', []]]),
      xrevrange: jest.fn().mockResolvedValue([['300-0', []]]),
    } as unknown as AppIORedisClient;
    const service = new CampaignServingSnapshotService(
      repository,
      configService,
      searchRedis
    );

    const gap = await (
      service as unknown as {
        hasStreamGap(cursor: string): Promise<boolean>;
      }
    ).hasStreamGap('100-0');

    expect(gap).toBe(true);
  });

  it('keeps the previous COW snapshot when a gap rebuild fails', async () => {
    const initial = { ...buildCampaign('c1'), servingVersion: 1 };
    const repository = buildRepository([]);
    const searchRepository = {
      getAllSearchCampaigns: jest
        .fn()
        .mockResolvedValueOnce([initial])
        .mockRejectedValueOnce(new Error('search unavailable')),
      findCampaignsByIds: jest.fn(),
    } as unknown as CampaignSearchRepository;
    const service = new CampaignServingSnapshotService(
      repository,
      configService,
      undefined,
      searchRepository
    );
    await service.findCampaignsByIds(['c1']);

    await expect(
      (
        service as unknown as {
          rebuildSnapshot(): Promise<void>;
        }
      ).rebuildSnapshot()
    ).rejects.toThrow('search unavailable');

    await expect(service.findCampaignsByIds(['c1'])).resolves.toEqual([
      expect.objectContaining({ id: 'c1', servingVersion: 1 }),
    ]);
  });
});
